Add doctor functionality
CloudElementsOpenLabs/formulas pull request #10
Opened 2020-10-12 18:54 UTC by kiawnna

@nick-bair @RickyAmparoCloud

2020-10-12 19:15 UTC, nick-bair commented on GettingAllResultsFromLoop/README.md
> +* The formula will be slow if you have a lot of contacts, and you might need to click the `CONTINUE POLLING` button in the steps pane after receiving a yellow warning message that the formula has sto
@kiawnna "The formula may take a few minutes to run, depending on the number of contacts"

2020-10-12 19:19 UTC, nick-bair commented on GettingAllResultsFromLoop/README.md
> +1. Insure you have the latest non-beta version of the doctor installed via npm. You can follow the directions found here (https://www.npmjs.com/package/ce-util/v/2.2.5) or run the command `npm instal
@kiawnna replace 'insure' with 'ensure'

2020-10-12 19:20 UTC, nick-bair commented on GettingAllResultsFromLoop/README.md
> +1. Insure you have the latest non-beta version of the doctor installed via npm. You can follow the directions found here (https://www.npmjs.com/package/ce-util/v/2.2.5) or run the command `npm instal
@kiawnna is there a way to link to the doctor docs without using the version in the path?

2020-10-12 19:22 UTC, nick-bair commented on HowToUseBulkWithinAFormula/TheDoctor/MyContactVDR/MyContact/MyContact.json
> +    "vdrVersion": "v2"
@kiawnna is it worth mentioning something about VDR v2 in the readme?  Or would this work in someone's org if they were on v1?

2020-10-12 19:26 UTC, nick-bair commented on HowToUseBulkWithinAFormula/README.md
> +    * If using the example VDR for **Example 2**, you will need to authenticate an element instance of one of the above (`Salesforce` or `Microsoft Dynamics CRM`) as well as an instance of `Google Dr
Update 'Microsofrt' to 'Microsoft'

2020-10-12 19:34 UTC, nick-bair commented on GettingAllResultsFromLoop/TheDoctor/Loop_Step_Aggregation.json
> +      }
@kiawnna please remove this step from the template (even though its inactive its part of the template).

2020-10-12 19:36 UTC, nick-bair commented on GettingAllResultsFromLoop/TheDoctor/Loop_Step_Aggregation.json
> +        }
@kiawnna What do you think about logging the output of the aggregator step here?  I think the current code isn't needed.

2020-10-12 19:37 UTC, nick-bair commented on GettingAllResultsFromLoop/TheDoctor/Loop_Step_Aggregation.json
> +          "body": "let arr = steps.aggregator ? steps.aggregator.arr : [];\narr.push(steps.contactsLoop.entry.Full_Name);\n\ndone({arr:arr});"
@kiawnna can you update the call you done likeso? `done({ arr })`.

2020-10-12 19:38 UTC, nick-bair requested changes
@kiawnna Excellent work, thanks for tackling this1  Commented on a few small items.

2020-10-12 21:54 UTC, kiawnna commented on GettingAllResultsFromLoop/README.md
> +1. Insure you have the latest non-beta version of the doctor installed via npm. You can follow the directions found here (https://www.npmjs.com/package/ce-util/v/2.2.5) or run the command `npm instal
done.

2020-10-12 21:55 UTC, kiawnna commented on GettingAllResultsFromLoop/README.md
> +* The formula will be slow if you have a lot of contacts, and you might need to click the `CONTINUE POLLING` button in the steps pane after receiving a yellow warning message that the formula has sto
done.

2020-10-12 21:55 UTC, kiawnna commented on GettingAllResultsFromLoop/README.md
> +1. Insure you have the latest non-beta version of the doctor installed via npm. You can follow the directions found here (https://www.npmjs.com/package/ce-util/v/2.2.5) or run the command `npm instal
done.

2020-10-12 21:56 UTC, kiawnna commented on HowToUseBulkWithinAFormula/README.md
> +    * If using the example VDR for **Example 2**, you will need to authenticate an element instance of one of the above (`Salesforce` or `Microsoft Dynamics CRM`) as well as an instance of `Google Dr
done!

2020-10-12 21:58 UTC, kiawnna commented on GettingAllResultsFromLoop/TheDoctor/Loop_Step_Aggregation.json
> +          "body": "let arr = steps.aggregator ? steps.aggregator.arr : [];\narr.push(steps.contactsLoop.entry.Full_Name);\n\ndone({arr:arr});"
@nick-bair Should I update all the call to done({ arr:arr }) or just this one?

2020-10-12 22:02 UTC, kiawnna commented on GettingAllResultsFromLoop/TheDoctor/Loop_Step_Aggregation.json
> +      }
done!

2020-10-12 22:03 UTC, kiawnna commented on HowToUseBulkWithinAFormula/TheDoctor/MyContactVDR/MyContact/MyContact.json
> +    "vdrVersion": "v2"
@nick-bair I will downgrade tomorrow and check it out (unless you want to test...?) Either way is fine!

2020-10-13 11:43 UTC, kiawnna commented on GettingAllResultsFromLoop/TheDoctor/Loop_Step_Aggregation.json
> +        }
done!

2020-10-13 11:49 UTC, kiawnna commented on GettingAllResultsFromLoop/TheDoctor/Loop_Step_Aggregation.json
> +          "body": "let arr = steps.aggregator ? steps.aggregator.arr : [];\narr.push(steps.contactsLoop.entry.Full_Name);\n\ndone({arr:arr});"
done.

2020-10-13 12:10 UTC, kiawnna commented on HowToUseBulkWithinAFormula/TheDoctor/MyContactVDR/MyContact/MyContact.json
> +    "vdrVersion": "v2"
done!

2020-10-13 12:19 UTC, kiawnna commented
Fixed, committed, and added the changes to my master branch. Verify? :)

2020-10-13 20:16 UTC, nick-bair approved these changes
Excellent @kiawnna

2020-10-13 20:17 UTC, merged