added third bulk formula for catching errors and updated readme
CloudElementsOpenLabs/formulas pull request #13
Opened 2020-11-13 15:58 UTC by kiawnna

also replaced the microsoft dynamics transformation with one from sugar crm

2020-11-13 15:58 UTC, kiawnna commented
@nick-bair @RickyAmparoCloud can't add you as a reviewer.

2020-11-13 18:50 UTC, nick-bair commented on HowToUseBulkWithinAFormula/README.md
> +    * **NOTE:** If you choose `Sugar CRM` as the source Element and `Salesforce` as the target, it's important to know that `Salesforce` does not allow for duplicate records to be created. Attempting
@kiawnna love this!

2020-11-13 18:51 UTC, nick-bair commented on HowToUseBulkWithinAFormula/BulkStep2.json
> +  "name": "BulkStep2",
@kiawnna should we remove 'Act-On' from the description?

2020-11-13 18:55 UTC, nick-bair commented on HowToUseBulkWithinAFormula/README.md
> +Working with bulk a Formula can be challenging. Bulk by nature is an asynchronous job, while Formulas are a synchronous procedure. The trick to getting them to work together is webhooks.
@kiawnna  "The trick to getting them to work together is webhooks." should be "The trick to getting them to work together is bulk job callbacks" or something.  Calling it webhooks might confuse customers who associate that with event-driven formulas.

2020-11-13 18:56 UTC, nick-bair commented on HowToUseBulkWithinAFormula/README.md
> +In this example, we will use three Formulas--one creates the bulk job, specifying who to notify when the job completes, one which recieves the 'job done' notification and consumes the results, and la
@kiawnna update to 'and notify you in the case that they occur'

2020-11-13 18:58 UTC, nick-bair commented on HowToUseBulkWithinAFormula/README.md
>      * Enter a cron job schedule (`0 0/10 0 ? * * *` will poll every 10 minutes).
@kiawnna Should we change this to a manual trigger?  My concern with a 10 minute cron is customers forget to turn it off.

2020-11-13 19:01 UTC, nick-bair commented on HowToUseBulkWithinAFormula/TheDoctor/Formulas/BulkStep3.json
> +        "description": "Enter an email to be notified in case of Bulk Upload failure.",
@kiawnna Is there a step missing for the email notification?  Or are you using the failed execution notification?

2020-11-13 19:01 UTC, nick-bair requested changes
Thanks @kiawnna couple of comments below

2020-11-16 12:23 UTC, kiawnna commented on HowToUseBulkWithinAFormula/README.md
> +    * **NOTE:** If you choose `Sugar CRM` as the source Element and `Salesforce` as the target, it's important to know that `Salesforce` does not allow for duplicate records to be created. Attempting
whoot whoot!

2020-11-16 12:23 UTC, kiawnna commented on HowToUseBulkWithinAFormula/BulkStep2.json
> +  "name": "BulkStep2",
yup! done!

2020-11-16 12:23 UTC, kiawnna commented on HowToUseBulkWithinAFormula/README.md
> +Working with bulk a Formula can be challenging. Bulk by nature is an asynchronous job, while Formulas are a synchronous procedure. The trick to getting them to work together is webhooks.
done!

2020-11-16 12:23 UTC, kiawnna commented on HowToUseBulkWithinAFormula/README.md
> +In this example, we will use three Formulas--one creates the bulk job, specifying who to notify when the job completes, one which recieves the 'job done' notification and consumes the results, and la
done!

2020-11-16 12:23 UTC, kiawnna commented on HowToUseBulkWithinAFormula/README.md
>      * Enter a cron job schedule (`0 0/10 0 ? * * *` will poll every 10 minutes).
I agree. Changed to manual trigger and update readme.

2020-11-16 14:30 UTC, kiawnna commented on HowToUseBulkWithinAFormula/TheDoctor/Formulas/BulkStep3.json
> +        "description": "Enter an email to be notified in case of Bulk Upload failure.",
odd. I thought I had handled it all in that step. Updated so check it out now!

2020-11-16 17:55 UTC, nick-bair approved these changes
@kiawnna LGTM!

2020-11-16 17:55 UTC, merged